### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Simon-Spettmann** [sorachan/opencast-downloader#1]
Traceback (most recent call last):
File "C:\ ... \opencast-downloader-master\opencast-downloader-master\oc_download.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

System: Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32

**Comment by sorachan** [comment]
Excuse me, I mistakenly assumed all imports were built-in modules, but this is not the case for _requests_. `pip3 install requests` should fix the problem.

**Comment by sorachan** [comment]
I've released a new version which automatically installs _requests_ if necessary. Let me know if this works for you.
