### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by luckydonald** [sorachan/opencast-downloader#2]
https://github.com/sorachan/opencast-downloader/blob/11b65b2ceb8c1b05a73f13aeaac36855a36aea0e/oc_download.py#L46-L50

`$ python3 oc_download.py`
```py
 File "oc_download.py", line 46
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
```

Seems like you committed without resolving them merge conflicts.

**Comment by sorachan** [comment]
Hi luckydonald, you beat me to it – I noticed the problem earlier today, but didn't get around to correcting the faulty commit until just now. I just force pushed the commit I originally intended, so this issue should be resolved.
